# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#configuration-options-for-the-dependabotyml-file

version: 2

# Maintain all dependencies for Composer
# updates:
#   - package-ecosystem: "composer"
#     directory: "/"
#     schedule:
#       interval: "weekly"
#     allow:
#       - dependency-type: "all"
#
# Maintain only certain deps for pip
#   - package-ecosystem: "pip"
    # directory: "/"
    # schedule:
    #   interval: "weekly"
    # allow:
    #   # Allow only direct updates for
    #   # Django and any packages starting "django"
    #   - dependency-name: "django*"
    #     dependency-type: "direct"
    #   # Allow only production updates for Sphinx
    #   - dependency-name: "sphinx"
    #     dependency-type: "production"

updates:
  # Supported package managers:
      # bundler
      # cargo
      # composer
      # docker
      # mix
      # elm
      # gitsubmodule
      # github-actions
      # gomod
      # gradle
      # maven
      # npm
      # nuget
      # pip, pipenv, pip-compile, poetry (use 'pip')
      # pub
      # terraform
      # yarn (use 'npm')
  - package-ecosystem: "gradle"
    directory: "client/java"
    schedule:
    # intervals: daily, weekly, monthly
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "integration/flink"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "integration/spark"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "client/python"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "integration/common"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "integration/airflow"
    schedule:
      interval: "weekly"  

  - package-ecosystem: "pip"
    directory: "integration/dbt"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "integration/sql"
    schedule:
      interval: "weekly"