---
name: Lint Code Base

on:
  push:
    branches-ignore: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint==2.14.3
          pip install astroid==2.11.6
          pip install typing_extensions==4.0.1
          pip install importlib-metadata==4.11.3

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for headers
        run: |
          ok=true
          readarray -t files <<<"$(jq -r '.[]' <<<'${{ steps.files.outputs.all }}')"
          for file in ${files[@]}; do 
            if [[ ($file == *".py") ]]; then
              if ! grep -q Copyright "$file"; then
                $ok=false
                echo "Copyright header not found in $file"
              fi
            fi
          done
          if [[ $ok == false ]]; then
            exit 1
          fi           


